# Generated by Django 5.2.6 on 2025-09-28 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('museum_parts', '0001_initial'),
        ('museum_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='responsible_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibitions', to='museum_users.employee'),
        ),
        migrations.AddField(
            model_name='exposition',
            name='exhibits',
            field=models.ManyToManyField(related_name='expositions', to='museum_parts.exhibit'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='exposition',
            field=models.ManyToManyField(to='museum_parts.exposition'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibitions', to='museum_parts.hall'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_parts.hall'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='museum_users.client'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum_parts.ticket'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='ticket',
            field=models.ManyToManyField(related_name='exhibitions', to='museum_parts.ticket'),
        ),
        migrations.AddField(
            model_name='cart',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum_parts.ticket'),
        ),
        migrations.AddField(
            model_name='tour',
            name='exhibitions',
            field=models.ManyToManyField(related_name='tours', to='museum_parts.exhibition'),
        ),
        migrations.AddField(
            model_name='tour',
            name='responsible_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='museum_users.employee'),
        ),
        migrations.AddField(
            model_name='tour',
            name='ticket',
            field=models.ManyToManyField(related_name='tours', to='museum_parts.ticket'),
        ),
    ]
