# Generated by Django 5.2.6 on 2025-09-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_parts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='price',
        ),
    ]
