# Generated by Django 5.2.6 on 2025-09-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_parts', '0003_remove_exhibit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='ticket_prices',
        ),
    ]
