# Generated by Django 5.2.6 on 2025-11-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.IntegerField(default=5, verbose_name='Задержка между слайдами (сек)')),
                ('loop', models.BooleanField(default=True, verbose_name='Зациклить слайдер')),
                ('show_navs', models.BooleanField(default=True, verbose_name='Показывать стрелки')),
                ('show_pagination', models.BooleanField(default=True, verbose_name='Показывать пагинацию')),
                ('auto_play', models.BooleanField(default=True, verbose_name='Автопереключение')),
                ('stop_on_hover', models.BooleanField(default=True, verbose_name='Останавливать при наведении')),
            ],
            options={
                'verbose_name': 'Настройка слайдера',
                'verbose_name_plural': 'Настройки слайдера',
            },
        ),
    ]
