# Generated by Django 5.2.6 on 2025-11-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='parent_consent',
            field=models.BooleanField(default=False),
        ),
    ]
